'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let toastTimeout;
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>$('#toast').classList.remove('visible'),3500)}
const storage={get(key,fallback=''){try{return localStorage.getItem(key)??fallback}catch{return fallback}},set(key,value){try{localStorage.setItem(key,value);return true}catch{return false}}};
function json(key,fallback){try{return JSON.parse(storage.get(key))??fallback}catch{return fallback}}
function clock(){const d=new Date();$('#clock').textContent=d.toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'});$('#clock').dateTime=d.toISOString();$('#date').textContent=d.toLocaleDateString('tr-TR',{day:'numeric',month:'long',weekday:'long'});const h=d.getHours();$('#greeting').textContent=h<6?'Gecenin kendi ritmi var.':h<12?'Güne sakin bir başlangıç.':h<18?'Biraz yavaşla.':'Günün gürültüsü geride kaldı.'}clock();setInterval(clock,1000);
const sceneNames={night:'01 / Gece kıyısı',dusk:'02 / Son ışıklar',forest:'03 / Yeşil sessizlik'};
function setScene(scene){if(!sceneNames[scene])scene='night';document.body.dataset.scene=scene;$('meta[name="theme-color"]').content={night:'#111526',dusk:'#31222e',forest:'#112c27'}[scene];$$('.scene-tabs button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.scene===scene)));$('#sceneName').textContent=sceneNames[scene];storage.set('emir-scene',scene)}
setScene(storage.get('emir-scene','night'));$$('.scene-tabs button').forEach(b=>b.onclick=()=>setScene(b.dataset.scene));
const notes=$('#notes');notes.value=storage.get('emir-notes');function noteCount(){$('#charCount').textContent=`${notes.value.length.toLocaleString('tr-TR')} karakter`}noteCount();
notes.addEventListener('input',()=>{noteCount();$('#saveStatus').textContent=storage.set('emir-notes',notes.value)?'Kaydedildi':'Kaydedilemedi';});
$('#exportNotes').onclick=()=>{const link=document.createElement('a');const url=URL.createObjectURL(new Blob([notes.value],{type:'text/plain;charset=utf-8'}));link.href=url;link.download='emir-gece-notlari.txt';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Notların indirildi.')};
let tasks=json('emir-tasks',[]);if(!Array.isArray(tasks))tasks=[];tasks=tasks.filter(t=>t&&typeof t.text==='string'&&typeof t.id==='string').slice(0,100);
function renderTasks(){const list=$('#taskList');list.replaceChildren();for(const task of tasks){const li=document.createElement('li'),label=document.createElement('label'),check=document.createElement('input'),span=document.createElement('span'),del=document.createElement('button');check.type='checkbox';check.checked=!!task.done;span.textContent=task.text;check.onchange=()=>{task.done=check.checked;saveTasks();renderTasks()};del.textContent='×';del.setAttribute('aria-label',`${task.text} görevini sil`);del.onclick=()=>{tasks=tasks.filter(t=>t.id!==task.id);saveTasks();renderTasks()};label.append(check,span);li.append(label,del);list.append(li)}$('#emptyTasks').hidden=tasks.length>0;$('#taskCount').textContent=tasks.filter(t=>!t.done).length}
function saveTasks(){if(!storage.set('emir-tasks',JSON.stringify(tasks)))toast('Tarayıcı kayıt alanına erişilemiyor. Görevlerin bu oturumda kalacak.')}
renderTasks();$('#taskForm').onsubmit=e=>{e.preventDefault();const text=$('#taskInput').value.trim();if(!text)return;if(tasks.length>=100){toast('Önce birkaç görevi sil; en fazla 100 görev tutulabilir.');return}tasks.push({id:crypto.randomUUID(),text,done:false});saveTasks();renderTasks();$('#taskInput').value=''};
function switchNotes(tasksOn){$('#notesPanel').hidden=tasksOn;$('#tasksPanel').hidden=!tasksOn;$('#notesTab').setAttribute('aria-pressed',String(!tasksOn));$('#tasksTab').setAttribute('aria-pressed',String(tasksOn));(tasksOn?$('#taskInput'):notes).focus()}
$('#notesTab').onclick=()=>switchNotes(false);$('#tasksTab').onclick=()=>switchNotes(true);
let timer=json('emir-timer-v2',null);if(!timer||![25,5,15].includes(timer.minutes)||!Number.isFinite(timer.left)||timer.left<0||timer.left>timer.minutes*60000||(timer.end!==null&&!Number.isFinite(timer.end)))timer={minutes:25,left:1500000,end:null};
let sessions=json('emir-sessions',{});if(!sessions||typeof sessions!=='object'||Array.isArray(sessions))sessions={};
function dayKey(){const d=new Date();return `${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`}
function saveTimer(){storage.set('emir-timer-v2',JSON.stringify(timer))}
function remaining(){return timer.end===null?timer.left:Math.max(0,timer.end-Date.now())}
function drawTimer(){const left=remaining(),seconds=Math.ceil(left/1000);$('#timer').textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;$('#progress').style.strokeDashoffset=515.222*(1-left/(timer.minutes*60000));$('#timerToggle').textContent=timer.end!==null?'Ⅱ   Duraklat':left===0?'↻   Yeniden':'▶   Başlat';$('#timerHint').textContent=timer.end!==null?(timer.minutes===25?'şimdi sadece bu an.':'nefes al. acele etme.'):left===0?'tamamlandı. iyi iş çıkardın.':'küçük bir adım yeter.';$('#sessionCount').textContent=`${Number(sessions[dayKey()])||0} seans`;$$('[data-minutes]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.minutes)===timer.minutes)));document.title=timer.end!==null?`${$('#timer').textContent} · emir.lol`:'emir.lol — gece istasyonu'}
function tick(){if(timer.end!==null&&remaining()<=0){timer.end=null;timer.left=0;if(timer.minutes===25){sessions[dayKey()]=(Number(sessions[dayKey()])||0)+1;storage.set('emir-sessions',JSON.stringify(sessions))}saveTimer();toast(timer.minutes===25?'Bir odak seansı tamamlandı. Şimdi biraz mola.':'Mola tamamlandı. Hazır olduğunda devam et.')}drawTimer()}
function toggleTimer(){if(timer.end!==null){timer.left=remaining();timer.end=null}else{if(timer.left<=0)timer.left=timer.minutes*60000;timer.end=Date.now()+timer.left}saveTimer();tick()}
$('#timerToggle').onclick=toggleTimer;$('#timerReset').onclick=()=>{timer.left=timer.minutes*60000;timer.end=null;saveTimer();drawTimer()};$$('[data-minutes]').forEach(b=>b.onclick=()=>{timer={minutes:Number(b.dataset.minutes),left:Number(b.dataset.minutes)*60000,end:null};saveTimer();drawTimer()});tick();setInterval(tick,250);document.addEventListener('visibilitychange',()=>{if(!document.hidden)tick()});
// Audio is generated locally, starts only with a user gesture, and never autoplays.
let audioContext;const channels={};
async function context(){const Constructor=window.AudioContext||window.webkitAudioContext;if(!Constructor)throw new Error('unsupported');if(!audioContext)audioContext=new Constructor();if(audioContext.state!=='running')await audioContext.resume();return audioContext}
const rainProfiles={soft:{cutoff:1200,gain:.75,drops:35,speed:.65},steady:{cutoff:2600,gain:1,drops:75,speed:1},heavy:{cutoff:4300,gain:1.25,drops:130,speed:1.5}};
let rainStyle=storage.get('emir-rain-style','steady');if(!rainProfiles[rainStyle])rainStyle='steady';$('#rainStyle').value=rainStyle;
function level(kind){return Number($(`#${kind}Volume`).value)/100*(kind==='drone'?.13:kind==='rain'?.48*rainProfiles[rainStyle].gain:.32)}
function updateSoundUI(){for(const b of $$('[data-sound]')){const active=!!channels[b.dataset.sound];b.setAttribute('aria-pressed',String(active));b.querySelector('.sound-toggle').textContent=active?'−':'+'}$('#soundState').textContent=Object.keys(channels).length?'SES AÇIK':'SES KAPALI';$('#quickRain').setAttribute('aria-pressed',String(!!channels.rain));$('#quickRain').textContent=channels.rain?'☂ Yağmur sesini kapat':'☂ Yağmur sesini aç'}
function stopSound(kind){const ch=channels[kind];if(!ch)return;delete channels[kind];ch.gain.gain.setTargetAtTime(0,audioContext.currentTime,.04);setTimeout(()=>{ch.nodes.forEach(n=>{try{n.stop()}catch{}n.disconnect()});ch.gain.disconnect()},200);updateSoundUI()}
const pending=new Set();let audioGeneration=0;
async function toggleSound(kind){if(channels[kind]){stopSound(kind);return}if(pending.has(kind))return;pending.add(kind);const generation=audioGeneration;try{const ctx=await context();if(generation!==audioGeneration)return;const gain=ctx.createGain();gain.gain.value=0;gain.connect(ctx.destination);const nodes=[];if(kind==='drone'){[130.81,164.81,196].forEach(f=>{const osc=ctx.createOscillator();osc.type='sine';osc.frequency.value=f;osc.connect(gain);osc.start();nodes.push(osc)})}else{const buffer=ctx.createBuffer(kind==='rain'?2:1,ctx.sampleRate*12,ctx.sampleRate);
for(let channel=0;channel<buffer.numberOfChannels;channel++){
const data=buffer.getChannelData(channel);let low=0,pink=0,tap=0,phase=0,frequency=1800;
for(let i=0;i<data.length;i++){
const white=Math.random()*2-1;low=(low+.02*white)/1.02;
if(kind==='brown'){data[i]=low*3.5;continue}
pink=.97*pink+.03*white;
if(Math.random()<.0018){tap=.12+Math.random()*.25;phase=0;frequency=900+Math.random()*2200}
phase+=2*Math.PI*frequency/ctx.sampleRate;tap*=.988;
const swell=.82+.1*Math.sin(2*Math.PI*i/data.length)+.08*Math.sin(6*Math.PI*i/data.length+channel);
data[i]=(white*.38+pink*1.7+low*.6+Math.sin(phase)*tap)*swell;
}}
const source=ctx.createBufferSource(),filter=ctx.createBiquadFilter();source.buffer=buffer;source.loop=true;filter.type='lowpass';filter.frequency.value=kind==='rain'?rainProfiles[rainStyle].cutoff:450;source.connect(filter);filter.connect(gain);source.start();nodes.push(source,filter);}channels[kind]={gain,nodes};gain.gain.setTargetAtTime(level(kind),ctx.currentTime,.2);updateSoundUI()}catch{toast('Ses başlatılamadı. Tarayıcının ses iznini kontrol edip tekrar dene.')}finally{pending.delete(kind)}}
$$('[data-sound]').forEach(b=>b.onclick=()=>toggleSound(b.dataset.sound));for(const kind of ['rain','brown','drone']){const range=$(`#${kind}Volume`),saved=Number(storage.get(`emir-volume-${kind}`,range.value));range.value=Number.isFinite(saved)?Math.max(0,Math.min(100,saved)):30;range.oninput=()=>{storage.set(`emir-volume-${kind}`,range.value);if(channels[kind])channels[kind].gain.gain.setTargetAtTime(level(kind),audioContext.currentTime,.05)}}
function mute(){audioGeneration++;Object.keys(channels).forEach(stopSound);sleepEnd=null;$('#sleepTimer').value='0';$('#sleepStatus').textContent=''}$('#muteAll').onclick=mute;
$('#quickRain').onclick=()=>toggleSound('rain');
$('#rainStyle').onchange=()=>{rainStyle=$('#rainStyle').value;storage.set('emir-rain-style',rainStyle);if(channels.rain){channels.rain.nodes[1].frequency.setTargetAtTime(rainProfiles[rainStyle].cutoff,audioContext.currentTime,.3);channels.rain.gain.gain.setTargetAtTime(level('rain'),audioContext.currentTime,.3)}resizeRain()};
let sleepEnd=null;
$('#sleepTimer').onchange=()=>{const minutes=Number($('#sleepTimer').value);sleepEnd=minutes?Date.now()+minutes*60000:null;updateSleep()};
function updateSleep(){if(sleepEnd===null){$('#sleepStatus').textContent='';return}const left=sleepEnd-Date.now();if(left<=0){mute();toast('Ses zamanlayıcısı tamamlandı. İyi dinlenmeler.');return}$('#sleepStatus').textContent=`Sesler ${Math.ceil(left/60000)} dakika sonra kapanacak.`}
setInterval(updateSleep,1000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)updateSleep()});
let zen=false;function setZen(value){zen=value;document.body.classList.toggle('zen',zen);$('#exitZen').hidden=!zen;$('#zen').setAttribute('aria-pressed',String(zen));(zen?$('#exitZen'):$('#zen')).focus();resizeRain()}$('#zen').onclick=()=>setZen(!zen);$('#exitZen').onclick=()=>setZen(false);
const canvas=$('#rain'),ctx=canvas.getContext('2d'),reduced=matchMedia('(prefers-reduced-motion: reduce)');let rainOn=!reduced.matches&&storage.get('emir-rain','1')==='1',raf=0,lastFrame=0,drops=[],width=0,height=0;
function resizeRain(){const rect=canvas.getBoundingClientRect();width=rect.width;height=rect.height;const dpr=Math.min(devicePixelRatio||1,2);canvas.width=width*dpr;canvas.height=height*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);drops=Array.from({length:Math.min(rainProfiles[rainStyle].drops,Math.round(width/10))},()=>({x:Math.random()*width,y:Math.random()*height,s:(4+Math.random()*6)*rainProfiles[rainStyle].speed}));renderRainState()}
function animate(now){if(!rainOn||document.hidden){raf=0;return}if(now-lastFrame>32){ctx.clearRect(0,0,width,height);ctx.strokeStyle='#e1dfea';ctx.lineWidth=.7;for(const d of drops){d.y+=d.s;d.x-=d.s*.25;if(d.y>height){d.y=-20;d.x=Math.random()*width}if(d.x<0)d.x=width;ctx.beginPath();ctx.moveTo(d.x,d.y);ctx.lineTo(d.x-3,d.y+14);ctx.stroke()}lastFrame=now}raf=requestAnimationFrame(animate)}
function renderRainState(){$('#motion').textContent=rainOn?'Yağmur açık':'Yağmur kapalı';$('#motion').setAttribute('aria-pressed',String(rainOn));if(raf){cancelAnimationFrame(raf);raf=0}ctx.clearRect(0,0,width,height);if(rainOn&&!document.hidden)raf=requestAnimationFrame(animate)}
function toggleRain(){rainOn=!rainOn;storage.set('emir-rain',rainOn?'1':'0');renderRainState()}$('#motion').onclick=toggleRain;new ResizeObserver(resizeRain).observe(document.documentElement);window.addEventListener('resize',resizeRain);document.addEventListener('visibilitychange',renderRainState);reduced.addEventListener('change',e=>{if(e.matches){rainOn=false;renderRainState()}});
const dialog=$('#commands'),search=$('#commandSearch');let previousFocus,selected=0;
const actions=[['Odak sayacını başlat / duraklat','Space',toggleTimer],['Sade görünümü aç / kapat','F',()=>setZen(!zen)],['Gece kıyısı','1',()=>setScene('night')],['Gün batımı','2',()=>setScene('dusk')],['Orman','3',()=>setScene('forest')],['Yağmur görüntüsünü aç / kapat','R',toggleRain],['Yağmur sesini aç / kapat','S',()=>toggleSound('rain')],['Tüm sesleri kapat','M',mute],['Not defterini aç','N',()=>{if(zen)setZen(false);switchNotes(false);notes.scrollIntoView({block:'center'})}]];
function commandButtons(){return $$('#commandList button')}
function markSelected(){commandButtons().forEach((b,i)=>b.classList.toggle('selected',i===selected))}
function renderCommands(){const list=$('#commandList');list.replaceChildren();selected=0;const query=search.value.toLocaleLowerCase('tr-TR');for(const [label,key,action]of actions.filter(a=>a[0].toLocaleLowerCase('tr-TR').includes(query))){const b=document.createElement('button'),span=document.createElement('span'),kbd=document.createElement('kbd');span.textContent=label;kbd.textContent=key;b.append(span,kbd);b.onclick=()=>{closeCommands();action()};b.onfocus=()=>{selected=commandButtons().indexOf(b);markSelected()};list.append(b)}if(!list.children.length){const p=document.createElement('p');p.className='empty';p.textContent='Bu komut bulunamadı.';list.append(p)}markSelected()}
function openCommands(){previousFocus=document.activeElement;search.value='';renderCommands();dialog.showModal();search.focus()}
function closeCommands(){dialog.close();if(previousFocus&&previousFocus.isConnected)previousFocus.focus()}
$('#commandOpen').onclick=openCommands;$('#commandClose').onclick=closeCommands;search.oninput=renderCommands;dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeCommands()}});
dialog.addEventListener('keydown',e=>{const buttons=commandButtons();if(['ArrowDown','ArrowUp'].includes(e.key)&&buttons.length){e.preventDefault();selected=(selected+(e.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length;markSelected();buttons[selected].scrollIntoView({block:'nearest'})}if(e.key==='Enter'&&document.activeElement===search&&buttons[selected]){e.preventDefault();buttons[selected].click()}});
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();dialog.open?closeCommands():openCommands();return}if(dialog.open)return;if(e.key==='Escape'&&zen){setZen(false);return}if(e.ctrlKey||e.metaKey||e.altKey||e.repeat||e.target.closest('input,textarea,select,button,a,[contenteditable]'))return;const key=e.key.toLowerCase();const action=actions.find(a=>a[1].toLowerCase()===(key===' '?'space':key));if(action){e.preventDefault();action[2]()}});
